version: 2.1

jobs:

  Test_aws_cli:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: testing aws cli from circleci
          command: |
            # aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            # aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            # aws configure set aws_session_token ""
            # It works fine
            cd test_circleci
            ./create.sh
            ./create_inventory.sh
            yum -y install tar
            yum -y install gzip
      - persist_to_workspace:
          root: test_circleci
          paths:
            - inventory
  Configure-with-ansible:
    parameters:
      fingerprint:
        type: string
        default: d5:ff:ce:90:1f:ba:cd:39:8a:86:5e:77:88:ae:7f:9a
    docker:
      - image: python:3.7-alpine3.11

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [<< parameters.fingerprint >>]
      - run:
          name: install ansible
          command: apk add --update ansible
      - attach_workspace:
          at: ws
      - run:
          name: Configuartion
          command: |
            cd ws
            ls
            ansible-playbook ans_main.yaml -i inventory
            ip=$(grep '^[0-9]$*' inventory)
            echo $ip

workflows:
  Example-Workflow:
    jobs:
      - Test_aws_cli
      - Configure-with-ansible:
          requires:
            - Test_aws_cli