Description: "Spins up an ec2 instance and attaches admin role to it"
# Comment

Resources:
        MyEc2Test:
                Type: "AWS::EC2::Instance"
                Properties:
                        ImageId: "ami-0ecc74eca1d66d8a6"
                        InstanceType: "t2.micro"
                        KeyName: 
                                Ref: "MyKey"
                        SecurityGroupIds:
                                - !GetAtt MySecGrp.GroupId
        MySecGrp:
                Type: "AWS::EC2::SecurityGroup"
                Properties:
                        GroupDescription: "Demo group"
                        SecurityGroupEgress:
                                - IpProtocol: "tcp"
                                  FromPort: 22
                                  ToPort: 22
                                  CidrIp: "0.0.0.0/0"
                        SecurityGroupIngress:
                                - IpProtocol: "tcp"
                                  FromPort: 22
                                  ToPort: 22
                                  CidrIp: "0.0.0.0/0"
                        VpcId: "vpc-04ead2cb76eff1c9c"
        MyKey:
                Type: "AWS::EC2::KeyPair"
                Properties:
                         KeyName: "privKey"
