- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install nginx"
  become: yes
  apt:
    name: [nginx]
    state: latest

- name: Copy index test page
  template:
    src: "files/index.html"
    dest: "/var/www/html/"

- name: starting nginx
  shell: |
    sudo service nginx restart